pipeline {
    agent any

    tools {
        maven 'Maven'// Replace with your Maven installation name in Jenkins
    
        jdk 'Java Home'
    }

    stages {
        stage('Build') {
            steps {
                bat cd SBSecurity && 'mvn clean compile'
            }
        }
        stage('Test') {
            steps {
                bat cd SBSecurity && 'mvn test'
            }
        }

        }
    }
